### ISSUE TITLE
How to handle errors in Effects?

### ISSUE THREAD

**Issue by sgrekov** [spotify/mobius#28]
Hi!
First of all, thank you for a great library!

One topic that I didn't find from the Wiki is how to handle errors from Effects properly.   
For example, if I use RxMobius, do I need to use .onErrorReturn operator from rx, and put a throwable into the Event, instead of resulting data?
`is GetSavedUserEffect -> prefs.getUserSavedCredentials()
                    .map { (login, pass) -> UserCredentialsLoadedEvent(login, pass) }
                    .onErrorReturn { return@onErrorReturn UserCredentialsLoadedEvent("", "", err = it) }`

**Comment by togi** [comment]
Hello!

Yes, you have the right idea - errors should be transformed into data as close as possible to where they happen. `onErrorReturn` is a good way to do that, but make sure you do it inside eg. a `flatMap` to prevent the entire chain chain from completing (`onErrorReturn` will complete its chain after emitting the one item).

Typically we would recommend that rather than forwarding the actual throwable, make is so that your effect handler translates the error into an event that in the domain of your loop describes what happened (eg. UserCredentialsLoadFailedNetworkErrorEvent or UserCredentialsLoadFailedNoSavedCredentialsEvent). Of course you could combine your different errors into one event that has an enum or sealed class as a parameter (ie. `UserCredentialsLoadFailedEvent(val error: ErrorType)`).

It's on our todo-list to write about more things like this on the wiki, so stay tuned!

**Comment by sgrekov** [comment]
Hey! Thanks for your answer!
I made something like that in my sample
https://github.com/sgrekov/AndroidMobiusSample/blob/master/app/src/main/java/com/sample/android/mobius/login/view/LoginFragment.kt#L190

One thing that worries me, is if I will create separate Event for error, this event must be subtype of normal event, right? That means I must do something like that:
`open class UserCredentialsLoadedEvent(val login: String, val pass: String) : LoginEvent()
data class UserCredentialsLoadedEventError(val err: Throwable? = null) : **UserCredentialsLoadedEvent("", "")**
`

**Comment by togi** [comment]
The error doesn't have to be a subtype of the even it is an error for, it can just be a direct subtype of `LoginEvent` in this case. We like doing it this way because then you know for sure that you've handled all error cases in your update function, because errors are then just regular events, and as such treated just like any other event in the update function.

By the way, I've only skimmed through your sample app so far, but I notice that you don't use `RxMobius.subtypeEffectHandler` to build your rx effect handler - I'd recommend having a look at it.

**Comment by pettermahlen** [comment]
I will close this issue as it has been answered, AFAICT. Please reopen if not!

**Comment by petergoczan** [comment]
This thread was really useful to me 👍
