### ISSUE TITLE
Conditionally subscribe/unsubscribe to event source?

### ISSUE THREAD

**Issue by sgrekov** [spotify/mobius#30]
Currently the way we can subscribe to event source is on the creating Loop stage. 
What if I want to subscribe(or unsubscribe) to event source only after specific state in the Model?

**Comment by pettermahlen** [comment]
I think there are two ways you can manage that:

1. Through ignoring all emitted events in some Model states, or
1. Through start/stop Effects that the Update function emits in some conditions. These Effects would be turning off and on the event source.

I think we'd be quite reluctant to add some sort of lifecycle to the `EventSource` API; it's good to keep things simple if possible. Does either of the above work for you? If not, could you describe your use case a little more?

**Comment by togi** [comment]
I'm guessing the background to this question is that in Elm, the `subscriptions` function (which is roughly equivalent to configuring event sources) is a function `model -> Sub Msg`, so changes in the model can be used to turn on or off event sources?

So far we haven't seen a very big need to turn on or off event sources during runtime, and the suggestions Petter made have been quite good at expressing the real-world scenarios we've run in to. In the most common case you listen to something like network state changes, and you can easily just drop events if you don't care about them.

If you have a "process" which emits multiple events during its lifetime and can be cancelled, then it's most likely a bit more complicated machine that the loop is controlling "remotely", and using effects to control that machine fits well with the idea of what effects are supposed to describe.

If you really want to have a mechanism that works like in Elm, you could in principle add an effect that takes the model as an argument, and build an operator that does some kind of `switchMap`y sort of things in RxJava to turn on and off observables.

If it would turn out to be a useful pattern for mobius, then it's possible a utility that helps you wire this together could be included in mobius-extra or mobius-rx, or be built as a 3rd party library for mobius, instead of changing the internal EventSource API.

**Comment by sgrekov** [comment]
@pettermahlen The most common use case is conditionally subscribe to some Observable. 
For example
 - when we open some screen we don't know exact _id_ of the entity, which we will get later after some http request. After we that we subscribe to Sqlite table to observe changes entities where this _id_ is parent
- subscribe to websocket observable, where the subscription request requires some incoming info

**Comment by pettermahlen** [comment]
For these use cases, I think you could consider modelling it as an effect handler. The subscription gets triggered by an effect with the ID/other incoming info. Or as a thing where there is a 'bridge' that is an event source, and an effect that triggers the subscription.

As @togi was saying, if this turns out to be a common scenario, we might add some utility for it, or describe it in the 'common patterns' section of the documentation that we're considering.

**Comment by sgrekov** [comment]
So, upstream must be something like Subject or Relay in order to have the ability to transfer data from outer objects? 
//this is our event source
val subject = Subject
            .just(false)
            .switchMap { startLoading ->
                getData(startLoading.uri) // this is something like an Observable<Result>
                    .map(result -> DataLoaded(result))
            }
        return subject.hide()
//this is our triggering effect
subject.accept(true)

**Comment by togi** [comment]
No, I meant it would be an effect registered in the subtypeEffectHandler:

```kotlin
val effectHandler =
    RxMobius.subtypeEffectHandler<Effect, Event>()
        .add(Effect.StartLoading::class.java,
            upstream -> upstream.switchMap { startLoading ->
                getData(startLoading.uri) // this is something like an Observable<Result>
                    .map(result -> DataLoaded(result))
        })
        .build()
```

**Comment by kaciula** [comment]
Hi. I also want to understand how to subscribe/unsubscribe to a stream in an effect handler.

For instance, I am using a Mobius controller and I call start/stop when the view is created/destroyed so that I can render the screen with the model as early as possible. However, when the view is visible (such as in onStart) I want to poll for something and stop when the view is no longer visible (such as in onStop).

I can create 2 events ViewStarted and ViewStopped in the corresponding methods and then, based on these, trigger an effect handler that starts/stops the polling. But I am at a loss on how to achieve this final part.

```
RxMobius
            .subtypeEffectHandler<Effect, Event>()
            .addTransformer(StartStopPolling::class.java, ::handleStartStopPolling)
            .build()

fun handleStartStopPolling(upstream: Observable<StartStopPolling>): Observable<UserDetailsEvent> {
        return upstream
            .flatMap {
                if (it.startPolling) {
                    // return a newly created polling stream
                    pollingStream()
                } else {
                    // how should I stop the polling stream here? should I keep a reference to the stream when it's being created and dispose of it here?
                   Observable.empty()  // is returning an empty observer ok here?
                }
            }
    }
```

Any guidance is appreciated. This library looks very promising. Great job! Can't wait to test it in production code.

**Comment by anawara** [comment]
@kaciula thanks! Sorry I didn't get back to you with an answer until now. Github didn't notify me for some reason 🤔  There's a couple of ways that you can use to achieve what you want I think. If you go through the solution you proposed, then I think what you need to do is use `switchMap` instead of `flatMap`.

Here's an example and explanation of how this works in RxJava
```Kotlin
// The effect handler
fun pollingHandler(u: Observable<StartStopPolling>) : Observable<Event> =
        u.switchMap { 
            // If we get a Start effect, we subscribe to the polling observable.
            if (it.start) poll() 
            // Otherwise we return an empty observable to cancel any previous subscriptions 
            // until we receive another start.
            else Observable.empty() 
        }

// The function we'll call when polling
fun readValue() = 1

// Poll every 5 minutes and pack the value into an event
fun poll() : Observable<PollReadEvent> = Observable.fromCallable { readValue() }
        .delaySubscription(5, TimeUnit.MINUTES, Schedulers.computation())
        .repeat()
        .startWith(readValue())
        .map { PollReadEvent(it) }
```
Here's how the above code behaves:
1. The first time you dispatch a `StartStopPolling(true)` effect from update, the effect handler is going to map that effect to the observable that does the polling. I just made a simple chain that calls a `readValue()` function every 5 minutes and packs its return into the appropriate event. 
2. The next time your update dispatches `StartStopPolling(false)`, the effect handler will map that to an empty observable. RxJava will then proceed to terminate the previous subscription it had created with the polling observable, and will not emit any more events since the new observable is empty. 
3. If you dispatch `StartStopPolling(true)` again, this will all repeat.

I think a simpler approach, IFF you don't really need to keep track of the view being available for interaction as part of your state, is to use an `EventSource` that is lifecycle aware which will automatically start polling when the view is started, and stops when the view is paused. Since you can get an `EventSource<T>` out of any `Observable<T>`, you could do something along the lines of
```kotlin
Observable<Lifecycle.State> lifecycleState = /* this should always emit the current state and all subsequent updates */
Observable<PollReadEvent> lifecycleAwarePollingObservable = lifecycleState.switchMap {
                if (it == RESUMED) poll()
                else Observable.empty()
        }
EventSource<Event> eventSource = EventSources.from(lifecycleAwarePollingObservable)
``` 

I hope I've answered your question! Let me know if there's anything else you'd like to know

**Comment by anawara** [comment]
@kaciula yours seems simpler :) I hadn't realized there was an `Observable.interval(initialDelay, ...)` :) 
TIL!

**Comment by anawara** [comment]
It's worth mentioning that we introduced a change that allows you to create event sources as `Connectable<Model, Event>`. What that means is the loop will connect to that connectable on start, then every time the model changes, the connection will be invoked and passed the new model. So if you want to subscribe to different sources based on what state you're in, you can use this approach.

**Comment by pettermahlen** [comment]
I think the `Connectable<Model, Event>` solution solves the original question, so closing this issue.
