### ISSUE TITLE
Unit test example

### ISSUE THREAD

**Issue by Ghedeon** [spotify/mobius#35]
Please, provide an example of what would be the right way of unit testing Mobius.
I've seen a few Hamcrest matchers in your presentation but, for example, I stopped using Hamcrest in favor of Atrium (fluent assertions). Probably, it would be beneficial to provide a generic way of testing Mobius, not bound to any particular framework. Here is an example of a simple test, that tries to assert the initial model in a stream.
```kotlin
import com.spotify.mobius.First
import com.spotify.mobius.Mobius
import com.spotify.mobius.MobiusLoop
import com.spotify.mobius.Next
import com.spotify.mobius.runners.WorkRunners
import com.spotify.mobius.rx2.RxConnectables
import com.spotify.mobius.rx2.RxMobius
import io.reactivex.Observable
import org.junit.Test

class MobiusUnitTest {

	private val loop: MobiusLoop.Factory<Model, Event, Effect> = RxMobius.loop(::update, ::effectHandler)
		.init { First.first(InitModel, setOf(InitEffect)) }
		.eventRunner { WorkRunners.immediate() }
		.effectRunner { WorkRunners.immediate() }

	private var controller: MobiusLoop.Controller<Model, Event> = Mobius.controller(loop, InitModel)

	private fun update(model: Model, event: Event): Next<Model, Effect> = when (event) {
		is InitEvent -> Next.next(InitModel)
	}

	private fun effectHandler(effects: Observable<Effect>): Observable<Event> = effects.flatMap { effect ->
		when (effect) {
			is InitEffect -> Observable.just(InitEvent)
		}
	}

	private fun bind(modelToEvent: (Observable<Model>) -> Observable<Event>) {
		controller.connect(RxConnectables.fromTransformer(modelToEvent))
		controller.start()
	}

	@Test
	fun should_receive_init_model() {
		bind { models: Observable<Model> ->
			val observer = models.test()

			// assert received model?? No model is received...

			Observable.empty<Event>()
		}
	}
}

sealed class Model
object InitModel : Model()

sealed class Event
object InitEvent : Event()

sealed class Effect
object InitEffect : Effect()
```
Would you be so kind to point out what's missing? Seems like `effectHandler` and `update` methods are being executed, but I'm still not getting the model in my receiver.

**Comment by sgrekov** [comment]
You can find some examples of unit testing with Mobius's specs in my sample
https://github.com/sgrekov/AndroidMobiusSample/blob/master/app/src/test/java/com/sample/android/mobius/login/presenter/LoginPresenterTest.kt

Still, not sure how much they are ideomatic..

**Comment by anawara** [comment]
@Ghedeon you can still use `InitSpec` and `UpdateSpec` without Hamcrest matchers. The signature for `then` is `then(Assert<M, F>)` where
```
/** Interface for defining your assertions over {@link Next} instances. */
public interface Assert<M, F> {
  void apply(Result<M, F> result);
}
```
So you could still write a test as follows:
```
spec.given(Model())
   .whenEvent(InitEvent)
   .then { result: Result<Model, Effect> ->
           val stateTransition = result.lastNext()
           // use whatever you would like to assert the model and set of effects in the next object
    }
```
One of the benefits of writing your logic in a pure function is that it makes testing a lot easier. The sample test you have is crossing the purity boundary and testing effect handlers as well. Of course, this is a valid test setup, but it isn't a unit test. We believe testing your update function in isolation as you would any pure function allows you to exhaustively test all desired behaviors without having to worry about mocking/faking system impurities in your test setup.

Hope this helps!

**Comment by anawara** [comment]
@sgrekov that's a good example :) I've actually just release 1.2.0 that adds a `whenEvent`/`whenEvents` to `UpdateSpec` to make it more Kotlin friendly

**Comment by sgrekov** [comment]
@anawara  Thanks! Will check them.

**Comment by Ghedeon** [comment]
Hmm... Thank you for the quick response! Please don't take my example as a representation of my project structure) I was trying to put up a bare minimum that will be copy&paste friendly, so it can be easily verified. The question still remains, tho, why this test is not working and how to test the whole loop?)

Talking about class responsibilities, all my mobius setup lives in a `ViewModel`, because I consider it unimportant implementation detail of a `ViewModel`, that shouldn't stick out. Basically, my expectation is:
1) There is a `ViewModel/Presenter` with Mobius inside
2) `ViewModel` exposes one single `bind` method: `fun bind(modelToEvent: (Observable<Model>) -> Observable<Event>)`, that is used by `Activity/Fragment`
3) `ViewModel` is a black box. In order to test it, I plug it in and observe how my external dependencies (mocks) react to different `Events` that I send.
Now, what you propose is to expose a public `Update` logic, that is hidden in my case, and test it separately. That looks a bit like an artificial workaround, similar to `@VisibleForTesting` but ok, no big deal. As a next step, how would I test the whole loop, with `Effects` actually triggering something? This `Update` function from the example above is not really plugged in and doesn't cover `EffectHandler`.

**Comment by Ghedeon** [comment]
Ok, found the problem with the initial example. Here is the working version, that tests initialization:
```kotlin
	@Test
	fun should_receive_init_model() {
		// mock external dependencies
		val observer = TestObserver.create<Model>()
		bind { models: Observable<Model> -> // imagine viewModel.bind() in a real world
			models.subscribe(observer)
			Observable.empty()
		}
		observer.assertValue(InitModel)
		// assert mocks
	}
```
Of course, could be wrapped in assertions/extensions but roughly that was the idea: to pull the stream and check the outcome.

**Comment by togi** [comment]
Testing the update function in isolation wasn't really referring to the fragment test reaching in and testing it or anything like that, just that the update function lives in its own class, and that there is a unit test for that class. In our own Java projects using Mobius we usually name this class FooLogic (where Foo is the feature name) and make the update function a static method.

The point @anawara tried to make is that the update function is very predictable and easy to test on its own. Likewise you can easily test the effect handler on it's own, and be very certain that it does what you expect it to do. You should only need a couple of system-level integration tests after that, since you otherwise mostly just would be testing that the Mobius frameworks is working correctly.

The separation of concerns encouraged by Mobius means you can be confident that your code does what it is expected to do as long as the update function and effect handler both are correct in isolation.


You can read a bit about how we think of Mobius and MV* frameworks [here](https://github.com/spotify/mobius/wiki/FAQ#is-mobius-an-alternative-to-mv), but I think in general we are sort of on the same page as you although it sounds like we put things in slightly different places. The way we usually hook up things is that we have some kind of FooViews class that holds onto the actual view hierarchy and is able to update the UI - this would be your "View" in MVP. We make it so that this class implements `Connectable<Model, Event>`, and have the fragment do `controller.connect(fooViews)`, which would be equivalent to the bind method you're describing. We sometimes map on a function that transforms the Model to some kind of ViewData object, so the view doesn't actually have to depend on the `Model` class. And if you really want to you can do the same thing on the output side to have it not depend on `Event`.

This approach doesn't really give you the kind of the black box ViewModel class that you're describing, but even so we still have a very distinct separation of concerns, minimal dependencies, and high testability. The `update` function only depends on the Model/Event/Effect data objects, each effect has an isolated effect handler that doesn't know about the other effects, the UI doesn't know anything about Mobius at all, and the fragment that wires it all together doesn't know anything about the implementation of either the view nor the effect handler.

Note that ViewModel from AAC can be used together with Mobius, but that's propably better to keep as a separate discussion. To get to the bottom of that you have to unpack what the ViewModel architecture component actually is doing, and that's a bit off-topic for this thread. The short version is basically that the AAC ViewModel isn't really a MVVM-"View Model", but rather a kind of retain-objects-during-configuration-changes-mechanism, and if there's anything you want to put in there it is probably parts of your effect handlers, not the entire Mobius loop or controller.

**Comment by anawara** [comment]
@Ghedeon glad to see you've found the issue. 

Another thing you could do to make this kind of test easier is add a listener directly to the `MobiusLoop` without using the controller and without using RxJava. We have a `RecordingModelObserver<S>` class that you can use and do things like `observer.assertStates("init", "init->first", "init->first->second")` so it does essentially the same thing you're doing but without the need to turn the loop into an RxJava observable.

**Comment by pettermahlen** [comment]
Adding to the previous comments, one reason for testing the update function in isolation is concurrency and event ordering - you never really know which order things are going to happen in, in a GUI application. Is the user going to type some more into the query field before the search response comes back? What if two backend responses are returned out of order? These kinds of sequencing problems are easy to test using `UpdateSpec` as its `when`/`whenEvents` methods take a number of events. So you can say something like:

```java
   spec
       .given(someInitialModel)
       .when(userTypesFirstQuery, userTypesSecondQuery, backendRespondsToSecondQuery, backendRespondsToFirstQuery)
       .then(secondResultsAreDisplayed);
```

Writing that kind of test when thinking of the viewmodel as a black box is likely to be harder.

**Comment by Ghedeon** [comment]
Thank you for all the comments, really appreciate the support from maintainers!
Everything about testing the `Update` is true, as long as that's your priority, and I'll definitely adopt the beforementioned techniques. 

Not to sound edgy, but I don't care that much about the `update` itself). It's pure, it doesn't provide side-effects. Nice to be tested separately, but it's simple and not very interesting. On the other hand, testing parts that produce side-effects is crucial in my opinion because that's where the real value of your code is. My system under test is `ViewModel` and it has a public interface that is subject to test. The goal of my test is to answer: _"are the side-effects of ViewModel expected ones"_? It could have inside a super long ping-pong exchange between `update` and `effectHandler`, but all I'll be listening for is _"was the repo/interactor mock called at the end"_? Similar to RxJava testing, yes, if the function is too big, it could be extracted and tested outside of the stream, but after that, if your interface provides an Observable, you better still plug-in the `TestObserver` and check the result. Just my two cents of reflection...)

I'd like to add, that the whole discussion is possible because Mobius is flexible enough to not impose a fixed structure: interfaces of my views and controllers are clean while being still highly testable. Therefore, don't you guys want to promote such an awesome framework a bit more?) I feel like it's not getting the attention it deserves. Before you jumped in with comments, I wasn't even sure "Is it alive? Was it just a spike? Are they keep using it at Spotify or maybe they changed they mind? What if I convince my team and it will deprecated soon?" Something to consider that would potentially improve the visibility: 

- Good sample app that will cover best practicies of Mobius usage & testing.
- Speak up to community. `kotlinlang.slack.com` and `android-united.slack.com` come to my mind. Both have android architecture channels and `#mobius` would a welcomed addition. While Mobius is not limited to kotlin, my impression is that `kotlinlang` is where the most exciting stuff is discussed. 

Thank you!

**Comment by pettermahlen** [comment]
I think in the particular case of my example, such a test as you're describing has the potential to be flaky: you would probably get `secondResultsDisplayed` in a model received by the observer, but then shortly afterwards you'd be getting the first results, if your business logic is incorrect. So if you're tests cover too large a functional area, then the risk of flakiness increases, and the precision of the tests' ability to pinpoint errors decreases. You've probably seen https://testing.googleblog.com/2015/04/just-say-no-to-more-end-to-end-tests.html - if not, at least I like those ideas. :) I think there is a sliding scale and you want tests at different levels, but most of them as small as you can make them. YMMV, of course, and it's true that the update functions are simple.

Thanks for the feedback about the framework and for the marketing suggestions! It would probably be good if we were better at marketing it. I'll be doing a talk at droidconBerlin about it, and @anawara has been submitting a couple of proposals to do talks at US conferences. And there will be a sample sometime real soon now (tm). So hopefully we'll be able to spread the word a bit.

**Comment by togi** [comment]
I'd just like to push a point a bit here - the core idea of mobius is that you _should_ care about the update function. It's where you make all decisions of what should happen when, so testing the update function is in fact where you make all assertions "are the side-effects the desired ones". Since the side-effects requested by the update function are represented as value types (effect objects), it's really easy to check that the update function made the right decision of what should happen. No need for mocks of any kind - just data in, data out.

Of course you have to make sure that the side-effect is implemented correctly too, but to do this you only have to check that the effect handler has the desired side-effect.

Since the update function already has done the heavy lifting of figuring out _which_ side-effect should happen, these tests just have to do simple assertions of the form "if I send an effect object _F_ to the effect handler, does it interact with the side-effecty mocks correctly (eg. does it try to interact with my repo or does it try to send a network request)".

**Comment by pettermahlen** [comment]
Closing this ticket, I think the original question has been answered.
