### ISSUE TITLE
MobiusLoop can't receive onActivityResult

### ISSUE THREAD

**Issue by Elforama** [spotify/mobius#42]
The current suggested way to setup Mobius is to call start() in onStart and stop() in onStop. This lifecycle doesn't allow the system to receive onActivityResult calls since it takes place before onStart calls start()

**Comment by DrewCarlson** [comment]
Not sure of other solutions but here is what I did to get file selection implemented.  As I noted [here](https://github.com/spotify/mobius/issues/38#issuecomment-415795014), my base (conductor) Controller is an EventSource for my UI mobius loop.  When the EventSource is subscribed to, the Controller will store the Consumer as a member until it is disposed of.  This Consumer is what I use to push `onActivityResult` events (among others) into the Loop.  As you noted this and other events can occur while the Loop is stopped, meaning no Consumer is available.  Instead of making the Consumer nullable, which would mean all events are lost while the Loop is stopped, I set it to a simple Consumer implementation that caches all events it receives.  This implementation also provides a method to empty the stored events into a new Consumer, this occurs when the EventSource is subscribed to, before replacing the old Consumer.

```kotlin
class QueuedConsumer<V> : Consumer<V> {

  private val queue = arrayListOf<V>()

  override fun accept(value: V) {
    queue.add(value)
  }

  fun dequeueAll(target: Consumer<V>) {
    queue.forEach(target::accept)
    queue.clear()
  }
}
```
```kotlin
abstract class BaseController(args: Bundle?) : Controller(args), EventSource<AppEvent> {

  var eventConsumer: Consumer<AppEvent> = QueuedConsumer()
    private set

  override fun subscribe(newConsumer: Consumer<AppEvent>): Disposable {
    (eventConsumer as? QueuedConsumer)?.dequeueAll(newConsumer)
    eventConsumer = newConsumer
    return Disposable {
      eventConsumer = QueuedConsumer()
    }
  }
}
```

**Comment by togi** [comment]
I understand that it's a bit confusing with the names - we chose start and stop for the names so that the controller would make sense outside of activity/fragment lifecycles, so unfortunately it doesn't actually have anything to do with `onStart()` or `onStop()`.

The recommended approach when using a controller in a fragment/activity is to use `onResume()` and `onPause()` for the lifecycle of the controller, as fragments will call `onSaveInstanceState()` before `onStop()` and you therefore might end up losing state if you keep the loop running past `onPause()` during eg. a configuration change. Of course there is nothing that prevents you from using `onStart()`/`onStop()` if you want or need to, but it does come with that caveat.

Regarding getting onActivityResult into the loop, using an EventSource as @DrewCarlson is suggesting is how we prefer to do it. There is in fact an example of this in the mobius-android-sample app. In the TaskFragment we are using an RxJava `BehaviorSubject`, like this:

https://github.com/spotify/mobius-android-sample/blob/master/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksFragment.java
```java
  private BehaviorSubject<TasksListEvent> mOnActivityResult = BehaviorSubject.create();

// ...

  @Override
  public void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (AddEditTaskActivity.REQUEST_ADD_TASK == requestCode && Activity.RESULT_OK == resultCode) {
      mEventSource.notifyEvent(taskCreated());
    }
  }
```

**Comment by pettermahlen** [comment]
@DrewCarlson one note about your QueuedConsumer implementation: since Mobius (and Android apps in general) use multiple threads, it would be a good idea to make it thread safe. Two easy ways of doing that are by making the `queue` a `Collections.synchronizedList` or by making the `accept` and `dequeueAll` methods `synchronized`. The latter is a bit safer, because it handles an unlikely  race if there is an `accept` while `dequeueAll` is being executed.

@togi the code you pasted has a bug. :) The `mOnActivityResult` field looks like it's unused. Instead, the `DeferredEventSource mEventSource` is what's handling the activity result. I'll create a PR to fix it.

Other than that, I agree with both the answers! :)

**Comment by pettermahlen** [comment]
Closing this, as I think it has been answered.
