### ISSUE TITLE
How to setup controller in ViewModel properly?

### ISSUE THREAD

**Issue by nominalista** [spotify/mobius#66]
First of all, thank you for open sourcing Mobius (and new Swift version also!), it's a great experience to introduce so many pure functions into own code.  

I wanted to ask something related to FAQ mentioned in Wiki - [Is Mobius an alternative to MV*?](https://github.com/spotify/mobius/wiki/FAQ#is-mobius-an-alternative-to-mv*). Assuming that we will use `ViewModel` from AAC as a VM layer, I was wondering how proper configuration of controller would look like in this layer. I found that it would be a good practice to separate the Mobius from the view elements completely and transfer it to the VM layer. It would have many benefits: view can observe only view model parts, not the whole model, events from UI can be transformed to business logic events or even effect handlers would be separated from the view layer. So I made a simple ViewModel:

```kotlin
class MyViewModel : ViewModel() {
    
    private lateinit var controller: MobiusLoop.Controller<MyModel, MyEvent>
    
    fun onCreate() {
        controller = // initialize controller here
        controller.connect(RxConnectables.fromTransformer { /* handle model here */ })
    }
    
    fun onStart() {
        controller.start()
    }
    
    fun onStop() {
        controller.stop()
    }
    
    fun onDestroy() {
        controller.disconnect()
    }
}
```

As you can see ViewModel needs to be aware of view lifecycle in order to properly connect/disconnect or start/stop the loop (method names could be different, but I named in this way to reflect the lifecycle methods in this example). It looks a little bit like a boiler plate to put these loop management in every ViewModel. I'm wondering, is there any drawback to extend the loop management to ViewModel lifecycle methods (init and onCleared) as it survives configuration changes? Or maybe it's not a good idea to setup controller inside ViewModel at all? I realize that Mobius gives a lot of flexibility and it's not a scope of the library to force any architecture constraints, but any opinions/help would be very appreciated in this topic.

**Comment by togi** [comment]
Hello!

A `MobiusLoop.Controller` serves two purposes: it allows you to break the dependency cycle `UI -> mobius -> UI`, and it allows you to stop and then resume a loop from where it left off. The first one isn't really necessary if you use LiveData, and the second one only makes sense in case you want to stop the loop while the hosting activity/fragment is stopped/recreated.

The important thing to know here is that stopping and restarting a loop will destroy the effect handler and cancel any ongoing requests. If you put you loop in a ViewModel I assume that's because you want to keep requests in-flight during configuration change, so you probably don't want that to stop the loop. For this reason, in a ViewModel I would most likely prefer using a loop directly without a controller. It might look a bit like this:

```kotlin
class MyViewModel(factory: MobiusLoop.Factory<MyModel, MyEvent, MyEffect>) : ViewModel() {
    
    private val loop = factory.startFrom(MyModel.createDefault());

    private val _model = MutableLiveData<MyModel>()
    val model : LiveData<MyViewModel> get() = _model
   
    init {
        loop.observe { _model.value = it }
    }

    override fun onCleared() {
        loop.dispose()
    }

    fun dispatchEvent(event: MyEvent) {
        loop.dispatchEvent(event)
    }
    
}
```

Keep in mind when using this pattern that the effect handler will leak your activity Context if it directly or indirectly has a reference to it, so be very careful with what dependencies you use in the effect handler.

**Comment by pettermahlen** [comment]
With https://github.com/spotify/mobius/pull/78 and a couple of follow-up PR:s, we now have a mechanism for directly supporting this. Please let us know if it helps and/or can be improved!

**Comment by wisnukurniawan** [comment]
hi @pettermahlen in https://github.com/spotify/mobius/blob/master/mobius-android/src/main/java/com/spotify/mobius/android/MobiusLoopViewModel.java#L64 there is new event type, why I need to create new model for that it will make a lot of model type in the end. 

Is there any document or sample code how to implement it correctly?

**Comment by pettermahlen** [comment]
I will let @ZenonSeth explain that, I think. :)

**Comment by ZenonSeth** [comment]
Hi @wisnukurniawan 

The `MobiusLoopViewModel` class is meant to be used instead of using a `MobiusLoopController`, and it provides similar functionality in that it runs the loop for you. There's a few important differences to how it's used.

First, since `MobiusLoopViewModel` extends the Android `ViewModel` it should be provided by a View Model Factory extending `ViewModelProvider.Factory`. 

In order to provide a `MobiusLoopViewModel` you would have to extend it, or if you're using Kotlin and also creating a Factory for each Fragment, it's possible to use a type-alias to make your code simpler.

The new event type `V` is the View Effects type, and it is used to communicate between the Loop and your View, by passing it into the `MobiusLoopViewModel` which then queues them up and emits them with Lifecycle awareness (done via the `getViewEffects()` method, see below)

The important thing to note here is that your loop components (either the Event Logic or the Effect Handler) should have NO direct reference to any Fragment or Views, but rather communicate to them via `ViewEffects`

In order to actually create a `MobiusLoopViewModel` you can use its static `create` function, which is very similar to how the Controller's `create` function works, with one difference. 

The create method doesn't take a factory, but a `Function` that returns a factory when it is given a `Consumer` of ViewEffects. This `Consumer` of ViewEffects is how your Effect Handler communicates to the view, instead of having a direct reference to the view.

Here's a simple example in Kotlin of a Factory for a _single_ Fragment and the creation of a `MobiusLoopViewModel`:

```kotlin
// this is used in Kotlin instead of inheriting to make it less verbose
typealias MyFragmentViewModel = MobiusLoopViewModel<
  MyFragmentDataModel,
  MyFragmentEvent,
  MyFragmentEffect,
  MyFragmentViewEffect>

class MyFragmentViewModelFactory(val initialModel: MyFragmentDataModel): ViewModelProvider.Factory {

  override fun <T : ViewModel?> create(modelClass: Class<T>): T =
      MyFragmentViewModel.create(provideLoopFactory(), initialModel, Init(::init)) as T

  private fun provideLoopFactory():
    Function<
      Consumer<MyFragmentViewEffect>, 
      MobiusLoop.Factory<MyFragmentDataModel, MyFragmentEvent, MyFragmentEffect>> =
        Function { consumer ->
            RxMobius.loop(Update(::update), MyFragmentEffectsHandler.create(consumer))
        }
}
```

The differences here:
1. Obviously instead of just providing a Loop Factory, we provide a Function that returns the LoopFactory.
2. Instead of providing an Effects Handler function, we have a class `MyFragmentEffectsHandler` that gives us the Effects Handler function once we give it a consumer. 

This is what this class might look like in Kotlin, and note that this is written with RxMobius as the loop runner:

```kotlin
class MyFragmentEffectHandler {
  fun create(viewEffectConsumer: Consumer<MyFragmentViewEffect>): ObservableTransformer<MyFragmentEffect, MyFragmentEvent> =
    RxMobius.subtypeEffectHandler<MyFragmentEffect, MyFragmentEvent>()
      .addAction(MyFragmentEffect.SavingCompleteled::class.java) {
        viewEffectConsumer.accept(MyFragmentViewEffect.ShowConfirmationDialog)
      }
```

In this case when a side-effect like `SavingCompleteled` is instead of invoking the View or Fragment directly, the effect handler sends a `MyFragmentViewEffect` that says that a dialog should be shown (as usual you can attach data to these if necessary)

These `ViewEffects` are then emitted, as properly tied to the lifecycle, by the `MobiusLoopViewModel`'s `viewEffect` function. The function returns an object called a `LiveQueue` which is simlar to `LiveData` in that it is tied to a Lifecycle, but it will queue view effects that happen in the background, and send them once something is listening to it again. To use it, in your Fragment you can write something like this:

```kotlin

// This functions is a shortcut for obtaining a ViewModel in a Fragment from the given factory
// it is necessary if a typealias is used. If inheriting from the MobiusLoopViewModel, this is not needed.
inline fun <reified T : ViewModel> Fragment.getViewModel(factory: ViewModelProvider.Factory) =
    ViewModelProvider(this, factory).get(T::class.java)

override fun onCreate(s: Bundle?) {
  //.. initialize some initial/empty initial model here first
  viewModel = getViewModel(MyFragmentViewModelFactory(someInitialModel))
}
override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View?  {
  //.. create the fragment's view here first
  viewModel.viewEffects.setObserver(
      viewLifecycleOwner,
      Observer { foregroundViewEffect -> view.accept(foregroundViewEffect) },
      Observer { backgroundViewEffects -> backgroundViewEffects.forEach { effect -> view.accept(effect) } }
  )
  return view
}
```

The `LiveQueue.setObserver` function is a bit different than the `addObserver` in the `LiveData` for two reasons:

1. You can only set 1 observer, setting a new one will replace the old one
2. You can specify two observers as you see above - the 1st one is manadatory, and will receive all `ViewEffects` that happen while your Fragment is in the `RESUMED` state. The 2nd observer is optional and it is where you will receive any and all `ViewEffects` that happen while your Fragment is `PAUSED`

There are some optimizations and shorthand functions for Kotlin-specific code that we're working on adding to the repo to reduce some boilerplate, but the above example sums up how you could set up a simple `MobiusLoopViewModel` class. Please let me know if you have any questions about this.
